apiVersion: v1
kind: Service
metadata:
  name: d10-sample-spring-boot-app-k8s
  labels:
    app: d10-sample-spring-boot-app-k8s
    backstage.io/kubernetes-id: d10-sample-spring-boot-app-k8s
spec:
  type: ClusterIP
  selector:
    app: d10-sample-spring-boot-app-k8s
  ports:
    - port: 8080
      protocol: TCP
      name: http